# Generated by Django 3.2.5 on 2021-08-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpostcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
    ]
